dashboard/application/dashboard/forms.py
# application/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, HiddenField, IntegerField

from wtforms.validators import DataRequired, Email


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    first_name = StringField('First name', validators=[DataRequired()])
    last_name = StringField('Last name', validators=[DataRequired()])
    email = StringField('Email address', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Register')

dashboard/application/__init__.py
import config
import os
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

login_manager = LoginManager()
bootstrap = Bootstrap()


def create_app():
    app = Flask(__name__, static_folder='static')

    environment_configuration = os.environ['CONFIGURATION_SETUP']
    app.config.from_object(environment_configuration)

    login_manager.init_app(app)
    login_manager.login_message = "You must be login to access this page."
    login_manager.login_view = "dashboard.login"

    bootstrap.init_app(app)

    with app.app_context():
        from .dashboard import bp
        app.register_blueprint(bp)

        return app

dashboard/application/dashboard/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard', __name__)

from . import routes

dashboard/application/dashboard/routes.py
import requests
from . import forms
from . import bp
from .api.authClient import authClient
from .. import login_manager
from flask import render_template, session, redirect, url_for, flash, request

from flask_login import current_user


@login_manager.user_loader
def load_user(user_id):
    return None


@bp.route('/', methods=['GET'])
def index():
    if current_user.is_authenticated:
        return render_template('dashboard.html')
    else:
        return redirect(url_for('dashboard.login'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = forms.RegistrationForm(request.form)
    if request.method == "POST":
        if form.validate_on_submit():
            username = form.username.data

            # Search for existing user
            user = authClient.does_exist(username)
            if user:
                # Existing user found
                flash('Please try another username', 'error')
                return render_template('register.html', form=form)
            else:
                # Attempt to create new user
                user = authClient.post_user_create(form)
                if user:
                    flash('Thanks for registering, please login', 'success')
                    return redirect(url_for('dashboard.login'))

        else:
            flash('Errors found', 'error')

    return render_template('register.html', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dashboard.index'))
    form = forms.LoginForm()
    if request.method == "POST":
        if form.validate_on_submit():
            api_key = authClient.post_login(form)
            if api_key:
                session['user_api_key'] = api_key
                user = authClient.get_user()
                session['user'] = user['result']

                flash('Welcome back, ' + user['result']['username'], 'success')
                return redirect(url_for('dashboard.index'))
            else:
                flash('Cannot login', 'error')
        else:
            flash('Errors found', 'error')
    return render_template('login.html', form=form)


@bp.route('/logout', methods=['GET'])
def logout():
    session.clear()
    return redirect(url_for('dashboard.login'))

dashboard/application/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}</dt>
<dd>
  {{ field(**kwargs)|safe }} {% if field.errors %}
  <ul class="errors">
    {% for error in field.errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</dd>
{% endmacro %}

dashboard/application/templates/_msgs.html
{% with messages = get_flashed_messages(with_categories=true) %} {% if messages
%}
<ul class="flashes">
  {% for category, message in messages %}
  <li class="alert text-center alert-{{ category }}" style="list-style: none">
    {{ message }}
  </li>
  {% endfor %}
</ul>
{% endif %} {% endwith %}

dashboard/application/templates/dashboard.html
{% extends "layout.html"%} {%block content%}
<script>
  let alert = false;
  if (!!window.EventSource) {
    var source = new EventSource("/temperature");
    var source2 = new EventSource("/electrical");
    var source3 = new EventSource("/oxygen");
    var source4 = new EventSource("/fire");
    source.onmessage = function (e) {
      $("#data").text(e.data);
      if (parseInt(e.data) >= 21)
        $("#temperature_id").css("background-color", "red");
      //else
      //$("#temperature_id").css("background-color","white");
    };
    source2.onmessage = function (e) {
      $("#electrical").text(e.data + "KW");
      if (parseInt(e.data) >= 1002)
        $("#eletrical_id").css("background-color", "red");
    };
    source3.onmessage = function (e) {
      $("#oxygen").text(e.data + "% O2");
      if (parseInt(e.data) <= 16)
        $("#oxygen_id").css("background-color", "red");
    };
    source4.onmessage = function (e) {
      $("#fire").text(e.data + "% CO2");
      if (parseInt(e.data) >= 200)
        $("#fire_id").css("background-color", "red");
    };
  }
  function silent_temperature() {
    $("#temperature_id").css("background-color", "white");
  }
  function silent_eletrical() {
    $("#eletrical_id").css("background-color", "white");
  }
  function silent_oxygen() {
    $("#oxygen_id").css("background-color", "white");
  }
  function silent_fire() {
    $("#fire_id").css("background-color", "white");
  }
  function fire_supression() {
    $("#fire_id").css("background-color", "red");
  }
  function oxygen_supression() {
    $("#oxygen_id").css("background-color", "red");
  }
  function lower_temperature() {
    $("#data").innerHTML=parseInt($("#data").innerHTML)-5;
  }
</script>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" style="color: #a22929">ISS CONTROLLER</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      class="collapse navbar-collapse d-flex justify-content-end"
      id="navbarNav"
    >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="/"
            style="color: #a22929 !important"
            >Dashboard</a
          >
        </li>
        {% if user == "admin" %}
        <li class="nav-item">
          <!-- TODO: Use URL For to redirect to register route -->
          <a
            class="nav-link"
            href="{{ url_for('dashboard.register') }}"
            style="color: #a22929"
            >Create user</a
          >
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link"
            href="{{ url_for('dashboard.logout') }}"
            style="color: #a22929"
            >Logout</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container1">{% include "_msgs.html"%}</div>
<div class="container">
  <div class="cards_wrapper">
    <div class="admin_container">
      <div class="card" id="fire_id">
        <h3 class="heading">Fire Monitoring <br>system</h3>
        <div class="reading">
          <p class="val">
            Reading:<span class="r_val"><span id="fire"></span></span>
          </p>
        </div>
        <div class="btn_wrapper">
          {% if user == "admin" %}
          <div><a href="#" onclick="fire_supression()" class="activate">Fire Suppression</a></div>
          <div>
            <a href="#" onclick="silent_fire()" class="activate"
              >Silence Alarm</a>
          </div>
          {%endif%}
        </div>
      </div>
      <div class="card" id="electrical_id">
        <h3 class="heading">Electrical Monitoring <br>system</h3>
        <div class="reading">
          <p class="val">
            Reading:<span class="r_val"><span id="electrical"></span></span>
          </p>
        </div>
        <div class="btn_wrapper">
          {% if user == "admin" %}
          <!--<div><a href="#" class="activate">Something</a></div>-->
          <div>
            <a href="#" onclick="silent_eletrical()" class="activate"
              >Silence Alarm</a>
          </div>
          {%endif%}
        </div>
      </div>
      <div class="card" id="temperature_id">
        <h3 class="heading">Temperature Monitoring <br>system</h3>
        <div class="reading">
          <p class="val">
            Reading:<span class="r_val"
              ><span id="data">No readings</span></span
            >
          </p>
        </div>
        <div class="btn_wrapper">
          {% if user == "admin" %}
          <div><a href="#" onclick="lower_temperature()" class="activate">Lower Temp</a></div>
          <div>
            <a href="#" onclick="silent_temperature()" class="activate"
              >Silence Alarm</a>
          </div>
          {%endif%}
        </div>
      </div>
      <div class="card" id="oxygen_id">
        <h3 class="heading">Oxygen Monitoring <br>system</h3>
        <div class="reading">
          <p class="val">
            Reading:<span class="r_val"
              ><span id="oxygen">No readings</span></span
            >
          </p>
        </div>
        <div class="btn_wrapper">
          {% if user == "admin" %}
          <div><a href="#" onclick="oxygen_supression()" class="activate">Activate Emer Oxy</a></div>
          <div>
            <a href="#" onclick="silent_oxygen()" class="activate"
              >Silence Alarm</a>
          </div>
          {%endif%}
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock content%}

dashboard/application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Material Design for Bootstrap fonts and icons -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons"
    />

    <!-- Material Design for Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/bootstrap-material-design.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />

    <title>{{title}}</title>
  </head>
  <body>
    {%block content%} {%endblock content%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{{url_for('static', filename='js/jquery-3.2.1.slim.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/popper.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap-material-design.js')}}"></script>
    <script>
      $(document).ready(function () {
        $("body").bootstrapMaterialDesign();
      });
    </script>
  </body>
</html>

dashboard/application/templates/login.html
{%extends "layout.html"%} {%block content%}
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4 mt-4">
      <div class="text-center h1 mb-3" style="color: brown">Login</div>
      {% include "_msgs.html"%} {% from "_formhelpers.html" import render_field %}
      <form method="post" enctype="multipart/form-data">
        <div>
          {{ form.hidden_tag() }}
          {{ render_field(form.username, class="form-control") }} 
          {{ render_field(form.password, class="form-control") }}
        </div>
        <p><input type="submit" value="Login" class="btn btn-info mt-3" /></p>
      </form>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
{%endblock content%}

dashboard/application/templates/register.html
{% extends "layout.html"%} {%block content%}
<div class="container">
  <div class="row mt-">
    <div class="col-md-2 mt-4"></div>
    <div class="col-md-8 mt-4">
      {% include "_msgs.html"%}
      <div class="text-center h1 mb-3" style="color: brown">Register</div>
      {% from "_formhelpers.html" import render_field %}
      <form method="POST" enctype="multipart/form-data">
        <div>
          {{ form.hidden_tag() }}
          {{ render_field(form.first_name, class="form-control", placeholder="Name") }} 
          {{ render_field(form.last_name, class="form-control", placeholder="Name") }} 
          {{ render_field(form.username, class="form-control", placeholder="Username") }} 
          {{ render_field(form.email, class="form-control", placeholder="Email") }}
          {{ render_field(form.password, class="form-control", placeholder="Password") }} 
          {{ render_field(form.submit, class="form-control") }}
        </div>
      </form>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
{%endblock content%}